// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: capsules.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCapsule = `-- name: CreateCapsule :one
INSERT INTO capsule (id, user_id, title, created_at, s3key, unlock_at, is_unlocked)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, created_at, s3key, unlock_at, is_unlocked
`

type CreateCapsuleParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Title      sql.NullString
	CreatedAt  time.Time
	S3key      string
	UnlockAt   time.Time
	IsUnlocked sql.NullBool
}

func (q *Queries) CreateCapsule(ctx context.Context, arg CreateCapsuleParams) (Capsule, error) {
	row := q.db.QueryRowContext(ctx, createCapsule,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.CreatedAt,
		arg.S3key,
		arg.UnlockAt,
		arg.IsUnlocked,
	)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.S3key,
		&i.UnlockAt,
		&i.IsUnlocked,
	)
	return i, err
}

const getCapsuleForUnlock = `-- name: GetCapsuleForUnlock :one
SELECT id, user_id, title, s3key, is_unlocked FROM capsule
WHERE id = $1 LIMIT 1
`

type GetCapsuleForUnlockRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Title      sql.NullString
	S3key      string
	IsUnlocked sql.NullBool
}

func (q *Queries) GetCapsuleForUnlock(ctx context.Context, id uuid.UUID) (GetCapsuleForUnlockRow, error) {
	row := q.db.QueryRowContext(ctx, getCapsuleForUnlock, id)
	var i GetCapsuleForUnlockRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.S3key,
		&i.IsUnlocked,
	)
	return i, err
}

const markAsUnlocked = `-- name: MarkAsUnlocked :exec
UPDATE capsule
SET is_unlocked = true
WHERE id = $1
`

func (q *Queries) MarkAsUnlocked(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAsUnlocked, id)
	return err
}
