// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Capsule struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Title      sql.NullString
	CreatedAt  time.Time
	S3key      string
	UnlockAt   time.Time
	IsUnlocked sql.NullBool
}

type Outbox struct {
	ID        uuid.UUID
	Payload   json.RawMessage
	Status    sql.NullString
	CreatedAt time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}
