// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox (id, payload, status, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, payload, status, created_at
`

type CreateOutboxEventParams struct {
	ID        uuid.UUID
	Payload   json.RawMessage
	Status    sql.NullString
	CreatedAt time.Time
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRowContext(ctx, createOutboxEvent,
		arg.ID,
		arg.Payload,
		arg.Status,
		arg.CreatedAt,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, payload, status, created_at FROM outbox
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutboxStatus = `-- name: UpdateOutboxStatus :exec
UPDATE outbox
SET status = $2
WHERE id = $1
`

type UpdateOutboxStatusParams struct {
	ID     uuid.UUID
	Status sql.NullString
}

func (q *Queries) UpdateOutboxStatus(ctx context.Context, arg UpdateOutboxStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOutboxStatus, arg.ID, arg.Status)
	return err
}
